server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookspace
    password: Parola14
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
